analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3279995371121913
  brandStrength: 1
  lightness: 0.7482845282647759
  brandColors:
    - '#050505'
    - '#01659A'
    - '#91A3BC'
    - '#D7D1CE'
    - '#91B44B'
  rhythmicContrast: 0.5273558273911476
typography_spectrum: 0.281362
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: '#PhotoJambo'
